euler87: euler87.c ../prime/libprime.a ../sets/libsets.a
	gcc -s -O3 euler87.c -o euler87.exe -lprime -L../prime -I../prime -lsets -L../sets -I../sets

euler87_d: euler87.c ../prime/libprime_d.a ../sets/libsets_d.a
	gcc -g euler87.c -o euler87_debug.exe -lprime_d -L../prime -I../prime -lsets -L../sets -I../sets