euler77: euler77.c ../prime/libprime.a
	gcc -s -O3 euler77.c -o euler77.exe -lprime -L../prime -I../prime

euler77_d: euler77.c ../prime/libprime_d.a
	gcc -g euler77.c -o euler77_debug.exe -lprime_d -L../prime -I../prime