euler118: euler118.o
	gcc -o euler118 euler118.o 

euler118.o: euler118.c
	gcc -c euler118.c -o euler118.o 

euler118_d: euler118_d.o
	gcc -o euler118_d euler118_d.o 

euler118_d.o: euler118.c
	gcc -g -c euler118.c -o euler118_d.o 


