euler74: euler74.c ../sets/libsets.a
	gcc -s -O3 euler74.c -o euler74.exe -lsets -L../sets -I../sets

euler74_d: euler74.c ../sets/libsets_d.a
	gcc -g euler74.c -o euler74_debug.exe -lsets_d -L../sets -I../sets