euler127: euler127.c
	gcc euler127.c -o euler127 -lprime -L../prime -I../prime

euler127_d: euler127.c
	gcc euler127.c -o euler127_d -g -lprime -L../prime -I../prime

check: check.c
	gcc check.c -o check -lprime -L../prime -I../prime

check_d: check.c
	gcc -g check.c -o check_d -lprime -L../prime -I../prime