euler88: euler88.c
#	gcc -s -O3 euler88.c -o euler88 -lsets -L../sets -I../sets -I../../timer -L../../timer -ltimer
	gcc -s -O3 euler88.c -o euler88

euler88_d: euler88.c ../sets/libsets_d.a
	gcc -g euler88.c -o euler88_d -lsets_d -L../sets -I../sets


euler88b_d: euler88b.c ../sets/libsets_d.a
	gcc -g euler88b.c -o euler88b_d -lsets_d -L../sets -I../sets