euler70: euler70.c ../sets/libsets.a ../prime/libprime.a
	gcc -s -O3 euler70.c -o euler70.exe -lsets -L../sets -I../sets -lprime -L../prime -I../prime

euler70_d: euler70.c ../sets/libsets_d.a ../prime/libprime_d.a
	gcc -g euler70.c -o euler70_debug.exe -lsets_d -L../sets -I../sets -lprime_d -L../prime -I../prime