euler95: euler95.c ../prime/libprime.a 
	gcc -s -O3 euler95.c -o euler95 -lprime -L../prime -I../prime -lm

euler95_d: euler95.c ../prime/libprime_d.a
	gcc -g euler95.c -o euler95_d -lprime_d -L../prime -I../prime -lm