euler111: euler111.c
	gcc -O5 -o euler111 euler111.c -lprime -L../prime -I../prime -I../../timer -I../sets -ltimer -L../../timer -lsets -L../sets

euler111_d: euler111.c
	gcc -g -o euler111_d euler111.c -lprime_d -L../prime -I../prime -I../../timer -I../sets -ltimer_d -L../../timer -lsets_d -L../sets -DDEBUG