euler65_d: euler65.c ../big_numbers/libbig_numbers_d.a ../big_numbers/big_numbers.h
	gcc -g euler65.c -o euler65_debug.exe -lbig_numbers_d -L../big_numbers -I../big_numbers

euler65: euler65.c ../big_numbers/libbig_numbers.a ../big_numbers/big_numbers.h
	gcc -s euler65.c -o euler65.exe -lbig_numbers -L../big_numbers -I../big_numbers
